# Generated by Django 5.2.5 on 2025-09-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='diskon',
            field=models.IntegerField(default=0),
        ),
    ]
