# Generated by Django 5.2.5 on 2025-10-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_shop_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('kaos adidas', 'Kaos Adidas'), ('sepatu merah', 'Sepatu Merah'), ('jersey', 'Jersey'), ('bola', 'Bola'), ('sepatu futsal', 'Sepatu Futsal')], max_length=50),
        ),
    ]
